name: Python Ruff Linting Pipeline

on:
    workflow_call:
        inputs:
            pythonVersion:
                description: 'Python Version'
                required: false
                default: '3.11'
                type: string

jobs:
    ruff-linting:
        name: Ruff Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ inputs.pythonVersion }}

            - name: Install Ruff
              run: |
                python -m pip install --upgrade pip
                pip install ruff

            - name: Run Ruff Lint and Save Output
              run: |
                ruff check . | tee ruff_output.txt

            - name: Upload Ruff Output as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ruff-lint-results
                path: ruff_output.txt

            - name: Display Ruff Lint Results
              run: |
                echo "Ruff Lint Results:"
                cat ruff_output.txt
