name: Python Pytest Pipeline

on:
  workflow_call:
    inputs:
      pythonVersion:
        description: 'Python Version'
        required: false
        default: '3.11'
        type: string
      testsAreRequired:
        description: 'whether tests are optional or not'
        required: false
        default: true
        type: boolean
      hasSubmodules:
        description: 'whether the repos has submodules'
        required: false
        default: false
        type: boolean

jobs:
    python-testing:
      name: Python Testing with Pytest
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ inputs.pythonVersion }}

        - name: Clone submodules
          if: ${{ inputs.hasSubmodules }}
          run: |
            git submodule update --init --recursive
            git submodule foreach 'git checkout main || echo "main branch not found in $name"'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
            pip install pytest

        - name: Run Pytest
          run: pytest

        - name: Upload Pytest Results (JUnit XML)
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: pytest-results
            path: pytest-results.xml
          continue-on-error: ${{ inputs.testsAreRequired }}
